function [pr] = trans(p,s,a)
if(s==1)
   if(a=='u') 
    if(p==s||p==s+1)
    pr=.1;
    elseif(p==9)
    pr=.8;
    else
    pr=0;    
    end
   elseif(a=='d')
    if(p==s+1)
    pr=.1;
    elseif(p==s)
    pr=.9;
    else
    pr=0;    
    end
   elseif(a=='l')
    if(p==s)
      pr=.9;  
    elseif(p==9)
    pr=.1;
    else
       pr=0; 
    end  
   elseif(a=='r')
    if(p==9||p==s)
        pr=.1;
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end
   end
elseif(s==2)
    if(a=='u'||a=='d') 
    if(p==s-1||p==s+1)
      pr=.1  ;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==s)
      pr=.2;  
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==s)
        pr=.2;
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==3)
    if(a=='u') 
    if(p==s-1||p==s+1)
      pr=.1;  
    elseif(p==8)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s-1||p==s+1)
      pr=.1;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==s||p==8)
        pr=.1;
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==8||p==s)
        pr=.1;    
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==4)
    if(a=='u') 
    if(p==s-1||p==s+1)
        pr=.1;
    elseif(p==7)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s+1||p==s-1)
        pr=.1;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==s||p==7)
        pr=.1;
    elseif(p==s-1)
        pr=.8;
    else
        pr=.0;
    end  
   elseif(a=='r')
    if(p==s||p==7)
        pr=.1;
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==5)
    if(a=='u') 
    if( p==s-1||p==s)
        pr=.1;
    elseif(p==6)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s-1)
        pr=.1;
    elseif(p==s)
        pr=.9;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==s||p==6)
        pr=0.1;
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==6)
        pr=.1;
    elseif(p==s)
        pr=.9;
    else
        pr=0;
    end
    end
elseif(s==6)
    if(a=='u') 
    if(p==s+1||p==s)
        pr=.1;
    elseif(p==14)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s||p==s+1)
        pr=.1;
    elseif(p==5)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==s-1||p==14)
        pr=.1;
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==14||p==s-1)
        pr=.1;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==7)
    if(a=='u') 
    if(p==s+1||p==s-1)
        pr=.1;
    elseif(p==13)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s-1||p==s+1)
        pr=.1;       
    elseif(p==4)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==4|p==13)
        pr=.1;
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==13|p==4)
        pr=.1;      
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==8)
    if(a=='u') 
    if(p==s||p==s-1)
      pr=.1;  
    elseif(p==12)
        pr=.8;
    else 
        pr=0;
    end
   elseif(a=='d')
    if(p==s||p==s-1)
        pr=.1;
    elseif(p==3)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==3||p==12)
       pr=.1; 
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==12||p==3)
        pr=.1;
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==9)
    if(a=='u') 
    if(p==s)
        pr=.2;
    elseif(p==10)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s)
        pr=.2;
    elseif(p==1)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l'||a=='r')
    if(p==1||p==10)
        pr=.1;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==10)
    if(a=='u') 
    if(p==s||p==s+1)
        pr=.1;
    elseif(p==16)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s+1||p==s)
     pr=.1;   
    elseif(p==9)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==9||p==16)
        pr=.1;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==16||p==9)
        pr=.1;
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==11)
    if(a=='u'||a=='d') 
    if(p==s-1||p==s+1)
     pr=.1;   
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==s)
     pr=.2;
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==s)
        pr=.2;
    elseif(p==s+1)
        pr=.8;
    else 
        pr=0;
    end
    end
elseif(s==12)
    if(a=='u') 
    if(p==s-1||p==s+1)
        pr=0.1;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s+1||p==s-1)
      pr=.1;  
    elseif(p==8)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==8||p==s)
        pr=.1;
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==8||p==s)
        pr=.1;
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==13)
    if(a=='u') 
    if(p==s-1||p==s+1)
        pr=.1;       
    elseif(p==15)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s-1||p==s+1)
        pr=.1; 
    elseif(p==7)
        pr=.8;
    else 
        pr=0;
    end
   elseif(a=='l')
    if(p==7||p==15)
        pr=.1;        
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==7||p==15)
        pr=.1;
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==14)
   if(a=='u') 
    if(p==s-1)
      pr=.1;
    elseif(p==s)
      pr=.9;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s||p==s-1)
        pr=.1;
    elseif(p==6)
        pr=.8;
    else
        pr=0;        
    end
   elseif(a=='l')
    if(p==6|p==s)
        pr=.1;
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;        
    end  
   elseif(a=='r')
    if(p==6)
        pr=.1;
    elseif(p==s)
        pr=.9;
    else
        pr=0;
    end
   end
elseif(s==15)
    if(a=='u') 
    if(p==s)
        pr=.2;
    elseif(p==20)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s)
        pr=.2;
    elseif(p==13)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l'||a=='r')
    if(p==13||p==20)
        pr=.1;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==16)
    if(a=='u') 
    if(p==s)
        pr=.2;
    elseif(p==17)
        pr=.8;
    else
        pr=0;        
    end
   elseif(a=='d')
    if(p==s)
        pr=.2;
    elseif(p==10)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l'||a=='r')
    if(p==10||p==17)
        pr=.2;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end  
   end
elseif(s==17)
    if(a=='u')
    if(p==s)
        pr=.9;
    elseif(p==s+1)
        pr=.1;
    else
    pr=0;
    end
   elseif(a=='d')
    if(p==s+1||p==s)
        pr=.1;
    elseif(p==16)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==16)
        pr=.1;
    elseif(p==s)
       pr=.9;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==s||p==16)
        pr=.1;       
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==18||s==19)
    if(a=='u'||a=='d') 
    if(p==s-1||p==s+1)
        pr=.1;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end   
   elseif(a=='l')
    if(p==s)
        pr=.2;
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==s)
        pr=.2;
    elseif(p==s+1)
      pr=.8;  
    else
        pr=0;
    end
    end
elseif(s==20)
    if(a=='u') 
    if(p==s-1||p==s+1)
        pr=.1;
    elseif(p==s)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='d')
    if(p==s-1||p==s+1)
        pr=.1;
    elseif(p==15)
        pr=.8;
    else
        pr=0;
    end
   elseif(a=='l')
    if(p==15||p==s)
        pr=.1;
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;        
    end  
   elseif(a=='r')
    if(p==15||p==s)
        pr=.1;
    elseif(p==s+1)
        pr=.8;
    else
        pr=0;
    end
    end
elseif(s==21)
    if(a=='u'||a=='d') 
    if(p==s-1)
        pr=.1;
    elseif(p==s)
        pr=.9;
    else
        pr=0;
    end   
   elseif(a=='l')
    if(p==s)
        pr=.2;
    elseif(p==s-1)
        pr=.8;
    else
        pr=0;
    end  
   elseif(a=='r')
    if(p==s)
        pr=1.;
    else
        pr=0;
    end
    end
end
